// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package br.ufs.dcomp.ChatRabbitMQ;

public final class ChatProtoBuf {
  private ChatProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 1;</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>required string date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required string time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 3;</code>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>optional string group = 4;</code>
     */
    boolean hasGroup();
    /**
     * <code>optional string group = 4;</code>
     */
    java.lang.String getGroup();
    /**
     * <code>optional string group = 4;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getContent();
    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code ChatRabbitMQ.Mensagem}
   */
  public  static final class Mensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatRabbitMQ.Mensagem)
      MensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      sender_ = "";
      date_ = "";
      time_ = "";
      group_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sender_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              date_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              time_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              group_ = bs;
              break;
            }
            case 42: {
              br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Builder.class);
    }

    public interface ConteudoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Mensagem.Conteudo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 1;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 1;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      /**
       * <code>required bytes body = 2;</code>
       */
      boolean hasBody();
      /**
       * <code>required bytes body = 2;</code>
       */
      com.google.protobuf.ByteString getBody();

      /**
       * <code>optional string name = 3;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 3;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 3;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Mensagem.Conteudo}
     */
    public  static final class Conteudo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ChatRabbitMQ.Mensagem.Conteudo)
        ConteudoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Conteudo.newBuilder() to construct.
      private Conteudo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Conteudo() {
        type_ = "";
        body_ = com.google.protobuf.ByteString.EMPTY;
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Conteudo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                type_ = bs;
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                body_ = input.readBytes();
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_Conteudo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder.class);
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private volatile java.lang.Object type_;
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BODY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString body_;
      /**
       * <code>required bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }

      public static final int NAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBody()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, body_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, body_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo)) {
          return super.equals(obj);
        }
        br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo other = (br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo) obj;

        boolean result = true;
        result = result && (hasType() == other.hasType());
        if (hasType()) {
          result = result && getType()
              .equals(other.getType());
        }
        result = result && (hasBody() == other.hasBody());
        if (hasBody()) {
          result = result && getBody()
              .equals(other.getBody());
        }
        result = result && (hasName() == other.hasName());
        if (hasName()) {
          result = result && getName()
              .equals(other.getName());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getType().hashCode();
        }
        if (hasBody()) {
          hash = (37 * hash) + BODY_FIELD_NUMBER;
          hash = (53 * hash) + getBody().hashCode();
        }
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ChatRabbitMQ.Mensagem.Conteudo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Mensagem.Conteudo)
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_Conteudo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder.class);
        }

        // Construct using br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          body_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor;
        }

        public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getDefaultInstanceForType() {
          return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance();
        }

        public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo build() {
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo buildPartial() {
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo result = new br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.body_ = body_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo) {
            return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo other) {
          if (other == br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance()) return this;
          if (other.hasType()) {
            bitField0_ |= 0x00000001;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasBody()) {
            setBody(other.getBody());
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000004;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            return false;
          }
          if (!hasBody()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string type = 1;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              type_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes body = 2;</code>
         */
        public boolean hasBody() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public com.google.protobuf.ByteString getBody() {
          return body_;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder setBody(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          body_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder clearBody() {
          bitField0_ = (bitField0_ & ~0x00000002);
          body_ = getDefaultInstance().getBody();
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 3;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Mensagem.Conteudo)
      }

      // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Mensagem.Conteudo)
      private static final br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo();
      }

      public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Conteudo>
          PARSER = new com.google.protobuf.AbstractParser<Conteudo>() {
        public Conteudo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Conteudo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Conteudo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Conteudo> getParserForType() {
        return PARSER;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sender_;
    /**
     * <code>required string sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object date_;
    /**
     * <code>required string date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string date = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object time_;
    /**
     * <code>required string time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string time = 3;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 4;
    private volatile java.lang.Object group_;
    /**
     * <code>optional string group = 4;</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string group = 4;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string group = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo content_;
    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getContent() {
      return content_ == null ? br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance() : content_;
    }
    /**
     * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder() {
      return content_ == null ? br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance() : content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContent().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, group_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getContent());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, group_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem other = (br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem) obj;

      boolean result = true;
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && getTime()
            .equals(other.getTime());
      }
      result = result && (hasGroup() == other.hasGroup());
      if (hasGroup()) {
        result = result && getGroup()
            .equals(other.getGroup());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Mensagem)
        br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.internal_static_ChatRabbitMQ_Mensagem_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem build() {
        br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem result = new br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.getDefaultInstance()) return this;
        if (other.hasSender()) {
          bitField0_ |= 0x00000001;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000004;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasGroup()) {
          bitField0_ |= 0x00000008;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSender()) {
          return false;
        }
        if (!hasDate()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        if (!getContent().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sender_ = "";
      /**
       * <code>required string sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string time = 3;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>optional string group = 4;</code>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string group = 4;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            group_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group = 4;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 4;</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000008);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 4;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        group_ = value;
        onChanged();
        return this;
      }

      private br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo content_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder> contentBuilder_;
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder setContent(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder setContent(
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder mergeContent(br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              content_ != null &&
              content_ != br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance()) {
            content_ =
              br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder getContentBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>required .ChatRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem.ConteudoOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Mensagem)
    }

    // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Mensagem)
    private static final br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.ChatProtoBuf.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Mensagem_Conteudo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\014ChatRabbitMQ\"\255\001\n\010Mensag" +
      "em\022\016\n\006sender\030\001 \002(\t\022\014\n\004date\030\002 \002(\t\022\014\n\004time" +
      "\030\003 \002(\t\022\r\n\005group\030\004 \001(\t\0220\n\007content\030\005 \002(\0132\037" +
      ".ChatRabbitMQ.Mensagem.Conteudo\0324\n\010Conte" +
      "udo\022\014\n\004type\030\001 \002(\t\022\014\n\004body\030\002 \002(\014\022\014\n\004name\030" +
      "\003 \001(\tB)\n\031br.ufs.dcomp.ChatRabbitMQB\014Chat" +
      "ProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatRabbitMQ_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatRabbitMQ_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Mensagem_descriptor,
        new java.lang.String[] { "Sender", "Date", "Time", "Group", "Content", });
    internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor =
      internal_static_ChatRabbitMQ_Mensagem_descriptor.getNestedTypes().get(0);
    internal_static_ChatRabbitMQ_Mensagem_Conteudo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Mensagem_Conteudo_descriptor,
        new java.lang.String[] { "Type", "Body", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
